// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw2xf6u9cXMqhSr-XEcrw_vWP7i8srBTQ',
    appId: '1:181919615126:web:d788834ea90aabcc011ab7',
    messagingSenderId: '181919615126',
    projectId: 'planperfect-420200',
    authDomain: 'planperfect-420200.firebaseapp.com',
    storageBucket: 'planperfect-420200.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrKOj39Jdo5E7nvB7B6keBh_QzsspGCpg',
    appId: '1:181919615126:android:8e757bd3f6a9bfc0011ab7',
    messagingSenderId: '181919615126',
    projectId: 'planperfect-420200',
    storageBucket: 'planperfect-420200.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQseVqFmu5ub_VY8pgq5YbKOEkrQ3WemM',
    appId: '1:181919615126:ios:6ccbe5570f8afd72011ab7',
    messagingSenderId: '181919615126',
    projectId: 'planperfect-420200',
    storageBucket: 'planperfect-420200.appspot.com',
    iosClientId: '181919615126-vsq7g83e9m0vbkfhnfmkm98p62l8ovt6.apps.googleusercontent.com',
    iosBundleId: 'com.jackbowlin.PlanPerfect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQseVqFmu5ub_VY8pgq5YbKOEkrQ3WemM',
    appId: '1:181919615126:ios:718b01131607df93011ab7',
    messagingSenderId: '181919615126',
    projectId: 'planperfect-420200',
    storageBucket: 'planperfect-420200.appspot.com',
    iosBundleId: 'com.example.haghocks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw2xf6u9cXMqhSr-XEcrw_vWP7i8srBTQ',
    appId: '1:181919615126:web:4ed2a31bad6da5f3011ab7',
    messagingSenderId: '181919615126',
    projectId: 'planperfect-420200',
    authDomain: 'planperfect-420200.firebaseapp.com',
    storageBucket: 'planperfect-420200.appspot.com',
  );
}